export const courses = [
  {
    id: 1,
    type: "CRASH COURSE",
    title: "JEE & IIT Mastery Program",
    description: "This comprehensive course is tailored for aspiring IITians, focusing on in-depth JEE concepts, problem-solving strategies, and exam readiness.",
    img: "/1 (2).avif",
    price: 6000,
    offerPrice: 4000,
    discount: "20%",
    detailedDescription: {
      watchHours: 50,
      classes: 30,
      testSeries: 10,
      videos: 40,
      portionsCovered: "Kinematics, Thermodynamics, Waves, Optics, and more.",
    },
    info: "This comprehensive course is designed for students aiming to excel in competitive exams like JEE Advanced and Olympiads. Covering a robust curriculum, it includes live and recorded lectures, personalized mentorship, and advanced problem-solving techniques. With access to a structured video portal, practice exams, and exclusive study materials, this course ensures thorough preparation and concept mastery. Perfect for students in grades 9 to 12, it focuses on building a strong foundation for academic success.",
    videoPortal: [
      "Validity: 1600 days",
      "State of the art coverage of syllabus for JEE ADV & INPHO",
      "Complete access of Video Portal for JEE Mains, JEE Advanced & Olympiads (class 9th to 12th)",
      "Recorded & Live Classes",
      "Unseen tricks/methods for problem-solving",
    ],
    examPortal: [
      "1600 days",
      "1600 Practice Exams",
      "Access to INSP books [COPs] for JEE AND PHYSICS OLYMPIAD",
      "INSP premium for JEE Mains JEE Advanced & Olympiads",
      "AITS GTs [INSP special] + 1200 self-created JEE Advance level Mock Tests",
    ],
  },
  {
    id: 2,
    type: "CRASH COURSE",
    title: "JEE Excellence Academy",
    description: "Designed for future IITians, this course combines advanced theory lessons, practical applications, and strategic test-taking techniques.",
    img: "/1 (3).avif",
    price: 6000,
    offerPrice: 4800,
    discount: "20%",
    detailedDescription: {
      watchHours: 60,
      classes: 40,
      testSeries: 12,
      videos: 50,
      portionsCovered: "Hydrocarbons, Functional Groups, Polymers, and more.",
    },
    info: "This comprehensive course is designed for students aiming to excel in competitive exams like JEE Advanced and Olympiads. Covering a robust curriculum, it includes live and recorded lectures, personalized mentorship, and advanced problem-solving techniques. With access to a structured video portal, practice exams, and exclusive study materials, this course ensures thorough preparation and concept mastery. Perfect for students in grades 9 to 12, it focuses on building a strong foundation for academic success.",
    videoPortal: [
      "Validity: 1600 days",
      "State of the art coverage of syllabus for JEE ADV & INPHO",
      "Complete access of Video Portal for JEE Mains, JEE Advanced & Olympiads (class 9th to 12th)",
      "Recorded & Live Classes",
      "Unseen tricks/methods for problem-solving",
    ],
    examPortal: [
      "1600 days",
      "1600 Practice Exams",
      "Access to INSP books [COPs] for JEE AND PHYSICS OLYMPIAD",
      "INSP premium for JEE Mains JEE Advanced & Olympiads",
      "AITS GTs [INSP special] + 1200 self-created JEE Advance level Mock Tests",
    ],
  },
  {
    id: 3,
    type: "CRASH COURSE",
    title: "JEE Turbo Revision Program",
    description: "A fast-paced revision course designed to cover the entire JEE syllabus in a short time.",
    img: "/1 (1).avif",
    price: 5000,
    offerPrice: 3500,
    discount: "30%",
    detailedDescription: {
      watchHours: 40,
      classes: 20,
      testSeries: 8,
      videos: 30,
      portionsCovered: "Vectors, Algebra, Mechanics, and more.",
    },
    info: "Ideal for last-minute preparation, this course provides quick concept revision, exam tips, and mock tests to boost confidence. Designed for grades 11 and 12 students preparing for JEE Mains and Advanced.",
    videoPortal: [
      "Validity: 1000 days",
      "Rapid coverage of core syllabus topics",
      "Recorded & Live Sessions",
      "Tricks for solving JEE problems faster",
    ],
    examPortal: [
      "1000 Practice Exams",
      "Access to concise study materials",
      "Focused tests for high-scoring topics",
    ],
  },
  {
    id: 4,
    type: "FULL-YEAR COURSE",
    title: "JEE Pro Masterclass",
    description: "An extensive year-long course for JEE aspirants with live classes and personalized mentoring.",
    img: "/1 (4).avif",
    price: 10000,
    offerPrice: 7500,
    discount: "25%",
    detailedDescription: {
      watchHours: 120,
      classes: 80,
      testSeries: 25,
      videos: 90,
      portionsCovered: "Calculus, Modern Physics, Chemistry, and more.",
    },
    info: "This year-long program offers in-depth lessons, live doubt clearing, and weekly assessments. Tailored for serious JEE aspirants aiming for top ranks.",
    videoPortal: [
      "Validity: 365 days",
      "Comprehensive JEE Mains & Advanced content",
      "Interactive sessions with experts",
      "Access to premium resources",
    ],
    examPortal: [
      "Weekly mock tests",
      "Detailed performance analysis",
      "Full-length JEE Mains & Advanced tests",
    ],
  },
  {
    id: 5,
    type: "CRASH COURSE",
    title: "Physics Champion Program",
    description: "A targeted program focusing exclusively on Physics concepts and problem-solving.",
    img: "/1 (6).avif",
    price: 4500,
    offerPrice: 3200,
    discount: "29%",
    detailedDescription: {
      watchHours: 30,
      classes: 25,
      testSeries: 7,
      videos: 35,
      portionsCovered: "Electrostatics, Magnetism, Optics, and more.",
    },
    info: "Perfect for students needing additional focus on Physics, this course includes advanced techniques, practice sessions, and topic-specific assessments.",
    videoPortal: [
      "Complete access for JEE Physics",
      "Live interactive classes",
      "Exclusive tricks for solving tough Physics problems",
    ],
    examPortal: [
      "Physics mock tests",
      "Detailed analysis and feedback",
      "Focus on high-weightage topics",
    ],
  },
  {
    id: 6,
    type: "FULL-YEAR COURSE",
    title: "JEE Advanced Edge Program",
    description: "Focused on cracking JEE Advanced with high-quality study material and rigorous test series.",
    img: "/1 (6).avif",
    price: 15000,
    offerPrice: 12000,
    discount: "20%",
    detailedDescription: {
      watchHours: 150,
      classes: 100,
      testSeries: 30,
      videos: 120,
      portionsCovered: "Organic Chemistry, Electrochemistry, Advanced Math, and more.",
    },
    info: "A premium course for students targeting JEE Advanced. Includes specialized content, daily practice problems, and one-on-one mentoring.",
    videoPortal: [
      "Unlimited access to advanced modules",
      "Expert-led live classes",
      "Comprehensive problem-solving sessions",
    ],
    examPortal: [
      "30 full-length Advanced mock tests",
      "Chapter-wise quizzes",
      "Detailed solutions for all questions",
    ],
  },
];
