export const courses = [
  {
    id: 1,
    type: "CRASH COURSE",
    title: "Physics for JEE",
    description: "Master the fundamentals of Physics.",
    price: 5000,
    img: "/Options.svg",
    offerPrice: 4000,
    discount: "20%",
    detailedDescription: {
      watchHours: 50,
      classes: 30,
      testSeries: 10,
      videos: 40,
      portionsCovered: "Kinematics, Thermodynamics, Waves, Optics, and more.",
    },
    info: "This comprehensive course is designed for students aiming to excel in competitive exams like JEE Advanced and Olympiads. Covering a robust curriculum, it includes live and recorded lectures, personalized mentorship, and advanced problem-solving techniques. With access to a structured video portal, practice exams, and exclusive study materials, this course ensures thorough preparation and concept mastery. Perfect for students in grades 9 to 12, it focuses on building a strong foundation for academic success.",
    videoPortal: [
      "Validity: 1600 days",
      "State of the art coverage of syllabus for JEE ADV & INPHO",
      "Complete access of Video Portal for JEE Mains, JEE Advanced & Olympiads (class 9th to 12th)",
      "Recorded & Live Classes",
      "Unseen tricks/methods for problem-solving",
      
    ],
    examPortal: [
      "1600 days",
      "1600 Practice Exams",
      "Access to INSP books [COPs] for JEE AND PHYSICS OLYMPIAD",
      "INSP premium for JEE Mains JEE Advanced & Olympiads",
      "AITS GTs [INSP special] + 1200 self-created JEE Advance level Mock Tests",
    ],
  },
  {
    id: 2,
    type: "CRASH COURSE",
    title: "Organic Chemistry",
    description: "Deep dive into Organic Chemistry. ",
    img: "/Options.svg",
    price: 6000,
    offerPrice: 4800,
    discount: "20%",
    detailedDescription: {
      watchHours: 60,
      classes: 40,
      testSeries: 12,
      videos: 50,
      portionsCovered: "Hydrocarbons, Functional Groups, Polymers, and more. ",
    },
    info: "This comprehensive course is designed for students aiming to excel in competitive exams like JEE Advanced and Olympiads. Covering a robust curriculum, it includes live and recorded lectures, personalized mentorship, and advanced problem-solving techniques. With access to a structured video portal, practice exams, and exclusive study materials, this course ensures thorough preparation and concept mastery. Perfect for students in grades 9 to 12, it focuses on building a strong foundation for academic success.",
    videoPortal: [
      "Validity: 1600 days",
      "State of the art coverage of syllabus for JEE ADV & INPHO",
      "Complete access of Video Portal for JEE Mains, JEE Advanced & Olympiads (class 9th to 12th)",
      "Recorded & Live Classes",
      "Unseen tricks/methods for problem-solving",
      
    ],
    examPortal: [
      "1600 days",
      "1600 Practice Exams",
      "Access to INSP books [COPs] for JEE AND PHYSICS OLYMPIAD",
      "INSP premium for JEE Mains JEE Advanced & Olympiads",
      "AITS GTs [INSP special] + 1200 self-created JEE Advance level Mock Tests",
    ],
  },
  {
    id: 6,
    type: "CRASH COURSE",
    title: "Organic Chemistry",
    description: "Deep dive into Organic Chemistry. ",
    img: "/Options.svg",
    price: 6000,
    offerPrice: 4800,
    discount: "20%",
    detailedDescription: {
      watchHours: 60,
      classes: 40,
      testSeries: 12,
      videos: 50,
      portionsCovered: "Hydrocarbons, Functional Groups, Polymers, and more. ",
    },
    info: "This comprehensive course is designed for students aiming to excel in competitive exams like JEE Advanced and Olympiads. Covering a robust curriculum, it includes live and recorded lectures, personalized mentorship, and advanced problem-solving techniques. With access to a structured video portal, practice exams, and exclusive study materials, this course ensures thorough preparation and concept mastery. Perfect for students in grades 9 to 12, it focuses on building a strong foundation for academic success.",
    videoPortal: [
      "Validity: 1600 days",
      "State of the art coverage of syllabus for JEE ADV & INPHO",
      "Complete access of Video Portal for JEE Mains, JEE Advanced & Olympiads (class 9th to 12th)",
      "Recorded & Live Classes",
      "Unseen tricks/methods for problem-solving",
      
    ],
    examPortal: [
      "1600 days",
      "1600 Practice Exams",
      "Access to INSP books [COPs] for JEE AND PHYSICS OLYMPIAD",
      "INSP premium for JEE Mains JEE Advanced & Olympiads",
      "AITS GTs [INSP special] + 1200 self-created JEE Advance level Mock Tests",
    ],
  },
  {
    id: 5,
    type: "CRASH COURSE",
    title: "Organic Chemistry",
    description: "Deep dive into Organic Chemistry. ",
    img: "/Options.svg",
    price: 6000,
    offerPrice: 4800,
    discount: "20%",
    detailedDescription: {
      watchHours: 60,
      classes: 40,
      testSeries: 12,
      videos: 50,
      portionsCovered: "Hydrocarbons, Functional Groups, Polymers, and more. ",
    },
    info: "This comprehensive course is designed for students aiming to excel in competitive exams like JEE Advanced and Olympiads. Covering a robust curriculum, it includes live and recorded lectures, personalized mentorship, and advanced problem-solving techniques. With access to a structured video portal, practice exams, and exclusive study materials, this course ensures thorough preparation and concept mastery. Perfect for students in grades 9 to 12, it focuses on building a strong foundation for academic success.",
    videoPortal: [
      "Validity: 1600 days",
      "State of the art coverage of syllabus for JEE ADV & INPHO",
      "Complete access of Video Portal for JEE Mains, JEE Advanced & Olympiads (class 9th to 12th)",
      "Recorded & Live Classes",
      "Unseen tricks/methods for problem-solving",
      
    ],
    examPortal: [
      "1600 days",
      "1600 Practice Exams",
      "Access to INSP books [COPs] for JEE AND PHYSICS OLYMPIAD",
      "INSP premium for JEE Mains JEE Advanced & Olympiads",
      "AITS GTs [INSP special] + 1200 self-created JEE Advance level Mock Tests",
    ],
  },
  {
    id: 4,
    type: "CRASH COURSE",
    title: "Organic Chemistry",
    description: "Deep dive into Organic Chemistry. ",
    img: "/Options.svg",
    price: 6000,
    offerPrice: 4800,
    discount: "20%",
    detailedDescription: {
      watchHours: 60,
      classes: 40,
      testSeries: 12,
      videos: 50,
      portionsCovered: "Hydrocarbons, Functional Groups, Polymers, and more. ",
    },
    info: "This comprehensive course is designed for students aiming to excel in competitive exams like JEE Advanced and Olympiads. Covering a robust curriculum, it includes live and recorded lectures, personalized mentorship, and advanced problem-solving techniques. With access to a structured video portal, practice exams, and exclusive study materials, this course ensures thorough preparation and concept mastery. Perfect for students in grades 9 to 12, it focuses on building a strong foundation for academic success.",
    videoPortal: [
      "Validity: 1600 days",
      "State of the art coverage of syllabus for JEE ADV & INPHO",
      "Complete access of Video Portal for JEE Mains, JEE Advanced & Olympiads (class 9th to 12th)",
      "Recorded & Live Classes",
      "Unseen tricks/methods for problem-solving",
      
    ],
    examPortal: [
      "1600 days",
      "1600 Practice Exams",
      "Access to INSP books [COPs] for JEE AND PHYSICS OLYMPIAD",
      "INSP premium for JEE Mains JEE Advanced & Olympiads",
      "AITS GTs [INSP special] + 1200 self-created JEE Advance level Mock Tests",
    ],
  },
  {
    id: 3,
    type: "FULL SYLLABUS",
    title: "Math for NEET",
    description: "Focus on core math concepts. ",
    img: "/Options.svg",
    price: 5500,
    offerPrice: 4400,
    discount: "20%",
    detailedDescription: {
      watchHours: 45,
      classes: 35,
      testSeries: 85,
      videos: 30,
      portionsCovered: "Algebra, Calculus, Geometry, Probability, and more. ",
    },
    info: "This comprehensive course is designed for students aiming to excel in competitive exams like JEE Advanced and Olympiads. Covering a robust curriculum, it includes live and recorded lectures, personalized mentorship, and advanced problem-solving techniques. With access to a structured video portal, practice exams, and exclusive study materials, this course ensures thorough preparation and concept mastery. Perfect for students in grades 9 to 12, it focuses on building a strong foundation for academic success.",
    videoPortal: [
      "Validity: 1600 days",
      "State of the art coverage of syllabus for JEE ADV & INPHO",
      "Complete access of Video Portal for JEE Mains, JEE Advanced & Olympiads (class 9th to 12th)",
      "Recorded & Live Classes",
      "Unseen tricks/methods for problem-solving",
      
    ],
    examPortal: [
      "1600 days",
      "1600 Practice Exams",
      "Access to INSP books [COPs] for JEE AND PHYSICS OLYMPIAD",
      "INSP premium for JEE Mains JEE Advanced & Olympiads",
      "AITS GTs [INSP special] + 1200 self-created JEE Advance level Mock Tests",
    ],
  },
];
