# Generated by Django 5.1.4 on 2025-01-04 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lecture_note_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('portions', models.TextField()),
                ('watch_hours', models.CharField(max_length=50)),
                ('classes_length', models.CharField(max_length=50)),
                ('tests_length', models.CharField(max_length=50)),
                ('videos', models.CharField(max_length=50)),
                ('validity', models.IntegerField(default=365)),
                ('content_left_1', models.TextField(blank=True, null=True)),
                ('content_left_2', models.TextField(blank=True, null=True)),
                ('content_left_3', models.TextField(blank=True, null=True)),
                ('content_left_4', models.TextField(blank=True, null=True)),
                ('content_right_1', models.TextField(blank=True, null=True)),
                ('content_right_2', models.TextField(blank=True, null=True)),
                ('content_right_3', models.TextField(blank=True, null=True)),
                ('content_right_4', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('chapters', models.CharField(max_length=100)),
                ('contents', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=255)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses_app.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=500)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_videos', to='courses_app.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses_app.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses_app.course')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses_app.subject'),
        ),
    ]
