# Generated by Django 5.1.4 on 2025-01-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='classes_length',
            new_name='chapters',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='tests_length',
            new_name='classes',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='videos',
            new_name='studymaterials',
        ),
        migrations.RemoveField(
            model_name='course',
            name='discount',
        ),
        migrations.AddField(
            model_name='course',
            name='tests',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
    ]
