# Generated by Django 5.0.3 on 2025-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=20),
        ),
    ]
