# Generated by Django 5.0.3 on 2025-01-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
