# Generated by Django 5.1.4 on 2025-01-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_rename_classes_length_course_chapters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursedata',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
