# Generated by Django 5.1.4 on 2025-01-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_usercoursedata_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='lecture_note_path',
        ),
    ]
