# Generated by Django 5.1.4 on 2025-01-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_usercoursedata_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(default='JEE', max_length=255),
        ),
    ]
