# Generated by Django 5.1.4 on 2025-01-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_remove_chapter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='lecture_note_path',
            field=models.CharField(default='note', max_length=500),
            preserve_default=False,
        ),
    ]
