# Generated by Django 5.1.4 on 2025-01-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_subject_type'),
        ('courses_app', '0005_chapter_description_chapter_lecture_note_path'),
    ]

    operations = [
    ]
