import Navbar from "./components/navbar";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-0 p-0 font-instSansN overflow-x-hidden bg-teal-100 bg-opacity-40"  >
      
      <Navbar />
      <div className="bg-white">
      {children}
      </div>
      </body>
    </html>
  );
}
