version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: jeeneetpulse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build:
      context: ./backend      # Build the Django app from the backend folder
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app        # Mount the backend directory inside the container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:1234d@db:5432/jeeneetpulse
      - DEBUG=1

volumes:
  postgres_data:
